name: CI

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Set up Maven'
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'
      - name: 'Clean up SNAPSHOTs before cache'
        run: |
          find ~/.m2/repository/ -name '*SNAPSHOT' | xargs rm -rf || true
          if [[ "${{ runner.os }}" == "macOS" ]]; then
            brew cleanup || true
          fi
        shell: bash

      - name: 'Build with Maven'
        if: runner.os != 'Windows'
        run: ./mvnw clean install -V -B -D "maven.artifact.threads=64" -D "org.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"

      - name: 'Build with Maven'
        if: runner.os == 'Windows'
        run: ./mvnw.cmd clean install -V -B -D "maven.artifact.threads=64" -D "org.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
